[package]
name = "blocking-permit"
version = "0.1.0"
authors = ["David Kellum <dek-oss@gravitext.com>"]
edition = "2018"
license       = "MIT/Apache-2.0"
description   = "tokio blocking ergonomics prototype"

[dependencies]
futures = { version=">=0.3.0-alpha.17, <0.4", package="futures-preview" }
lazy_static = { version=">= 1.3.0, <1.4" }
log = { version=">=0.4.4, <0.5" }

tokio-sync = { git = "https://github.com/tokio-rs/tokio" }
tokio-threadpool = { git = "https://github.com/tokio-rs/tokio" }

[dev-dependencies]
env_logger = { version=">=0.6.0, <0.7", default-features=false }

[features]
current_thread=[] # testing hack
